---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bmlogit

<!-- badges: start -->
<!-- badges: end -->

The goal of `bmlogit` is to estimate the multinominal logistic regression with
prediction constraints.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("soichiroy/bmlogit")
```
## Example


```{r load_package, message=FALSE}
library(bmlogit)
library(emlogit)
library(synthArea)
```

```{r example}
## load data
data(cces_nc)
data(acs_nc)

## population data
target_Y <- acs_nc %>% count(educ, wt = N) %>% mutate(prop = n / sum(n)) %>% pull(prop)
pop_X <- model.matrix(~age + gender, data = acs_nc %>% count(age, gender, wt = N))[,-1]
count_N <- acs_nc %>% count(age, gender, wt = N) %>% pull(n)

## survey data
Y <- model.matrix(~educ-1, data = cces_nc)
X <- model.matrix(~age + gender, data = cces_nc)[,-1]

## fit
fit <- bmlogit(Y = Y, X = X, target_Y = target_Y, pop_X = pop_X, count_N = count_N,
               control = list(tol_pred = 0.01))


## multinominal logit without constraints
fit2 <- emlogit(Y = Y, X = X)



## result
res <- cbind(target_Y,
  predict(fit, newdata = pop_X, counts = count_N),
  as.vector(crossprod(predict(fit2, newdata = pop_X),  count_N / sum(count_N))),
  colMeans(Y)
)

knitr::kable(res, col.names = c("population", "bmlogit", "emlogit", "raw prop."),
             digits = 4)
```


```{r, dpi=450, fig.height=3.5, fig.width=7.5}
## coefficients
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), pty = 's')
for (i in 1:3) {
  plot(fit2$coef, fit$coef, pch = 16,
       xlab = "emlogit", ylab = "bmlogit",
       main = rownames(res)[i+1])
  abline(0, 1, col = 'gray', lty = 2)  
}
```



## Application to Post-Stratification


```{r}
# estimate state-wide quantity
data("districts_nc")
data(estimands_nc)

## turnout in NC
turnout <- sum(estimands_nc$totalvotes) / sum(estimands_nc$vap)

## raw estimate without adjustment
turnout_naive <- mean(cces_nc$vv_turnout)

## estimates stratified on educ, age, and gender
pop_tab <- acs_nc %>% count(educ, age, gender, wt = N) %>%
    mutate(weight = n / sum(n))
nonpar <- cces_nc %>% group_by(educ, age, gender) %>%
  summarise(turnout = sum(vv_turnout) / n(), .groups = "drop") %>%
  left_join(pop_tab, by = c("educ", "age", "gender")) %>%
  mutate(scale_weight = weight / sum(weight))
turnout_nonpar <- nonpar$scale_weight %*% nonpar$turnout


## bmlogit
pop_tab2 <- acs_nc %>% count(age, gender, wt = N) %>% mutate(prop = n / sum(n))

# compute the joint table
tmp  <- pop_tab2$prop
prYX <- apply(pop_X %*% bbs, 1, function(x) exp(x) / sum(exp(x)))  
pr_joint <- data.frame(t(sapply(1:length(tmp), function(i) prYX[,i] * tmp[i])))
colnames(pr_joint) <- c("HS or Less", "Some College", "4-Year", "Post-Grad")
pop_tab2 <- bind_cols(pop_tab2, pr_joint) %>%
  select(-n, -prop) %>%
  tidyr::pivot_longer(cols = c(`HS or Less`, `Some College`, `4-Year`, `Post-Grad`),
                      names_to = "educ", values_to = "weights")

# estimate with the estimated weigthts
weight_bmlogit <- cces_nc %>% group_by(educ, age, gender) %>%
  summarise(turnout = sum(vv_turnout) / n(), .groups = "drop") %>%
  left_join(pop_tab2, by = c("educ", "age", "gender")) %>%
  mutate(scale_weight = weights / sum(weights))
turnout_bmlogit <- weight_bmlogit$scale_weight %*% weight_bmlogit$turnout

## emlogit
pop_tab3 <- acs_nc %>% count(age, gender, wt = N) %>%  mutate(prop = n / sum(n))

# compute the joint table
tmp  <- pop_tab3$prop
prYX <- apply(pop_X %*% bb0, 1, function(x) exp(x) / sum(exp(x)))  
pr_joint <- data.frame(t(sapply(1:length(tmp), function(i) prYX[,i] * tmp[i])))
colnames(pr_joint) <- c("HS or Less", "Some College", "4-Year", "Post-Grad")
pop_tab3 <- bind_cols(pop_tab3, pr_joint) %>%
  select(-n, -prop) %>%
  tidyr::pivot_longer(cols = c(`HS or Less`, `Some College`, `4-Year`, `Post-Grad`),
                      names_to = "educ", values_to = "weights")

# estimate with the estimated weights
weight_emlogit <- cces_nc %>% group_by(educ, age, gender) %>%
  summarise(turnout = sum(vv_turnout) / n(), .groups = "drop") %>%
  left_join(pop_tab3, by = c("educ", "age", "gender")) %>%
  mutate(scale_weight = weights / sum(weights))
turnout_emlogit <- weight_emlogit$scale_weight %*% weight_emlogit$turnout



## results  
est <- c(turnout_naive, turnout_nonpar,
         turnout_bmlogit, turnout_emlogit)
estimator  <- c("Sample Mean", "Post-str. w/ True Joint",
                "Post-str. w/ bmlogit Joint",
                "Post-str. w/ emlogit Joint")
knitr::kable(
  cbind(estimator, round(est, 3), round(turnout, 3)),
  col.names = c("Estimator", "Estimate", "Truth"),
  digits = 3
)
```
